/* 
Write a program where a user must guess a random number between 1 and 20 generated by the computer and stored in a variable. If the user guesses too low, print to screen, "too low, guess again". If the user guesses too high, print to screen, "too high, guess again". Repeat this until the user has guessed the right number.
*/
import java.util.Random;
import java.util.Scanner;

public class HiloProgram {

	public static void main(String[] args) {

	Random  randomNumber = new Random();
	Scanner in = new Scanner(System.in);
	int guessedByUser = 0;
	int valueGenerated = randomNumber.nextInt(20) + 1;
	
	System.out.println("Welcome to the Hi/Lo Progamm");

	do {

	System.out.println("Please enter a number between 1 and 20 : ");
	guessedByUser = in.nextInt();
	
		if(guessedByUser < valueGenerated) {
			System.out.println("Your number entered " + guessedByUser + " is too Low! Guess again.");
		}
		
		if(guessedByUser > valueGenerated) {
			System.out.println("Your number entered " + guessedByUser + " is too High! Guess again.");
		}
	}

	while(guessedByUser != valueGenerated);

	System.out.println("Congratulation! The random number generated by the computer was : " + valueGenerated);

}
}

